"""YouTube cookie keeper - extracts cookies from a logged-in browser session."""
import logging
import os

import httpx

logger = logging.getLogger(__name__)

FLACFETCH_API_URL = "http://localhost:8080"


async def extract_netscape_cookies(context) -> str:
    """Extract YouTube/Google cookies from browser context in Netscape format for yt-dlp."""
    cookies = await context.cookies(["https://www.youtube.com", "https://www.google.com"])

    if not cookies:
        raise ValueError("No cookies found for YouTube/Google domains")

    lines = ["# Netscape HTTP Cookie File", "# This file was generated by flacfetch credential-keeper"]
    youtube_count = 0

    for c in cookies:
        domain = c["domain"]
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expiry = str(int(c.get("expires", 0)))
        name = c["name"]
        value = c["value"]
        lines.append(f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")

        if "youtube" in domain.lower() or "google" in domain.lower():
            youtube_count += 1

    if youtube_count == 0:
        raise ValueError("Cookies extracted but none for YouTube/Google domains")

    logger.info(f"Extracted {len(cookies)} cookies ({youtube_count} YouTube/Google)")
    return "\n".join(lines) + "\n"


async def upload_cookies(cookies_content: str) -> bool:
    """Upload cookies to flacfetch API and Secret Manager."""
    api_key = os.environ.get("FLACFETCH_API_KEY")
    if not api_key:
        logger.error("FLACFETCH_API_KEY not set, cannot upload cookies")
        return False

    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(
                f"{FLACFETCH_API_URL}/config/youtube-cookies",
                json={"cookies": cookies_content},
                headers={"X-API-Key": api_key},
                timeout=30,
            )

        if response.status_code == 200:
            logger.info(f"Cookies uploaded successfully: {response.json().get('message', '')}")
            return True
        else:
            logger.error(f"Cookie upload failed ({response.status_code}): {response.text}")
            return False
    except Exception as e:
        logger.error(f"Cookie upload error: {e}")
        return False


async def refresh_youtube_cookies(page, context) -> bool:
    """Navigate to YouTube to refresh cookies, then extract and upload them.

    Assumes the browser is already logged into Google.
    Returns True if cookies were successfully refreshed and uploaded.
    """
    try:
        # Visit YouTube to refresh session cookies
        logger.info("Navigating to YouTube to refresh cookies...")
        await page.goto("https://www.youtube.com", wait_until="domcontentloaded", timeout=30000)
        await page.wait_for_timeout(3000)

        # Check if we're logged in (look for avatar button, absence of sign-in)
        sign_in_button = await page.query_selector('a[aria-label="Sign in"]')
        if sign_in_button:
            logger.warning("Not logged into YouTube - Google session may have expired")
            return False

        # Extract and upload cookies
        cookies_content = await extract_netscape_cookies(context)
        return await upload_cookies(cookies_content)

    except Exception as e:
        logger.error(f"YouTube cookie refresh failed: {e}")
        return False
